dbt_poc:
  outputs:
    dev:
      account: vijpaot-uqb01557
      database: DB_DBT_POC
      password: Naren@2023
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 4
      type: snowflake
      user: narenkumar
      warehouse: COMPUTE_WH