name: Run dbt Models
 
on:
  push:
    branches:
      - main  # Change this to your main branch name
 
jobs:
  run-dbt:
    runs-on: windows-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: narenkumar57/Naren_DBT_Repo  # Corrected the repository URL
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
 
      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt
          pip install dbt-snowflake
 
      - name: Create Environment File
        run: |
          echo 'C:\Users\naren\Desktop\DBTCORE\DBT Project\dbt-env\Scripts' >> $GITHUB_PATH
          echo 'C:\Users\naren\.dbt' >> $GITHUB_PATH
          echo 'C:\Users\naren\Desktop\DBTCORE\DBT Project\dbt_poc' >> $GITHUB_PATH
      - name: Run dbt models
        run: |
          dbt run --profiles-dir C:\Users\naren\.dbt
